[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "N", "Q", "A"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
exclude = ["tests/"]

[[tool.mypy.overrides]]
module = ["innerloop.api.*"]
ignore_errors = true

[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
py_version = 311
force_sort_within_sections = true
src_paths = ["innerloop", "tests"]
