name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Show workspace (debug once; optional)
        run: ls -la
      - run: python -m pip install -U pip
      - run: |
          pip install \
            "fastapi>=0.111" "uvicorn>=0.30" \
            "pydantic>=2.7" "pydantic-settings>=2.3" \
            "httpx>=0.27" "pytest>=8.2" "pytest-timeout>=2.3.1" \
            "ruff>=0.5.0" "mypy>=1.10"
      - name: Lint
        run: ruff check gepa-next
      - name: Type check
        run: mypy gepa-next/innerloop
      - name: Tests (quick)
        run: pytest -q -k "health or sse" --maxfail=1
        env:
          PYTHONPATH: ${{ github.workspace }}/gepa-next
      - name: Tests (full)
        run: pytest -q
        env:
          PYTHONPATH: ${{ github.workspace }}/gepa-next
