name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Detect where the code actually lives: repo root (.) or ./gepa-next
      - name: Detect project directory
        run: |
          if [ -d "gepa-next/innerloop" ]; then
            echo "PROJ_DIR=gepa-next" >> "$GITHUB_ENV"
          else
            echo "PROJ_DIR=." >> "$GITHUB_ENV"
          fi
          echo "Using PROJ_DIR=${PROJ_DIR:-.}"
      
      - name: Show layout (debug)
        run: |
          pwd
          ls -la
          [ "$PROJ_DIR" = "gepa-next" ] && ls -la gepa-next || true

      - run: python -m pip install -U pip
      - name: Install deps
        run: |
          # core deps + sqlite persistence
          pip install \
            "fastapi>=0.111" "uvicorn>=0.30" \
            "pydantic>=2.7" "pydantic-settings>=2.3" \
            "httpx>=0.27" "pytest>=8.2" "pytest-timeout>=2.3.1" \
            "pytest-cov>=5.0" "aiosqlite>=0.20" \
            "ruff>=0.5.0" "mypy>=1.10" \
            "bandit>=1.7" "radon>=6.0"

      - name: Install Python client
        run: pip install -e clients/python

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: clients/js/package-lock.json

      - name: Build JS client
        run: |
          cd clients/js
          npm ci
          npm test
          npm run build
          cd ../..
      - name: Type check JS
        working-directory: clients/js
        run: npx tsc --noEmit

      - name: Lint
        run: ruff check "$PROJ_DIR"

      - name: Type check
        run: |
          if [ -d "$PROJ_DIR/innerloop" ]; then
            mypy "$PROJ_DIR/innerloop"
          else
            echo "innerloop/ not found under $PROJ_DIR; skipping mypy"
          fi

      - name: OpenAPI snapshot check (non-destructive on first run)
        run: |
          python tools/snapshot_openapi.py || (echo "::error ::OpenAPI drift detected. Run tools/snapshot_openapi.py --update locally and commit the snapshot." && exit 1)
        env:
          PYTHONPATH: ${{ github.workspace }}/${{ env.PROJ_DIR }}
        working-directory: ${{ env.PROJ_DIR }}

      - name: Schemathesis fuzz (exclude SSE stream endpoint)
        run: |
          schemathesis run \
            --app innerloop.main:app \
            --checks all \
            --hypothesis-max-examples=20 \
            --endpoint '^(?!/v1/optimize/.*/events).*$'
        env:
          PYTHONPATH: ${{ github.workspace }}/${{ env.PROJ_DIR }}
          OPENROUTER_API_KEY: dev
        working-directory: ${{ env.PROJ_DIR }}

      - name: Security scan
        run: bandit -r "$PROJ_DIR" -x "$PROJ_DIR/tests" -q

      - name: Complexity scan
        run: |
          radon cc -j "$PROJ_DIR"
          radon mi -j "$PROJ_DIR"

      - name: Tests (quick)
        run: pytest -q -k "health or sse" --maxfail=1
        env:
          PYTHONPATH: ${{ github.workspace }}/${{ env.PROJ_DIR }}
        working-directory: ${{ env.PROJ_DIR }}

      - name: Tests (full)
        run: pytest -q
        env:
          PYTHONPATH: ${{ github.workspace }}/${{ env.PROJ_DIR }}
        working-directory: ${{ env.PROJ_DIR }}

      - name: Mutation testing (focused)
        run: |
          mutmut run --no-progress --paths-to-mutate innerloop/domain/optimize_engine.py,innerloop/api/jobs/registry.py --tests-dir tests -j 2
          SURVIVED=$(mutmut results | awk '/^Survived/ {print $2}' || echo 0)
          echo "Survived mutants: $SURVIVED"
          # allow a couple initially; tighten later
          [ -z "$SURVIVED" ] && SURVIVED=0
          if [ "$SURVIVED" -gt 2 ]; then
            echo "::error ::More than 2 surviving mutants ($SURVIVED)."
            mutmut results
            exit 1
          fi
        env:
          PYTHONPATH: ${{ github.workspace }}/${{ env.PROJ_DIR }}
        working-directory: ${{ env.PROJ_DIR }}

      - name: pip-audit (dependencies)
        run: pip-audit -r requirements.txt

      - name: Generate SBOM (CycloneDX)
        run: cyclonedx-py -e -o sbom.json
        working-directory: ${{ env.PROJ_DIR }}

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: '0'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Secret scan (gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --no-git -v

      - name: Upload examples
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: |
            examples/
            docs/postman/

      - name: Upload QA artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qa-artifacts
          path: |
            ${{ env.PROJ_DIR }}/docs/openapi.snap.json
            ${{ env.PROJ_DIR }}/sbom.json
