name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Detect where the code actually lives: repo root (.) or ./gepa-next
      - name: Detect project directory
        run: |
          if [ -d "gepa-next/innerloop" ]; then
            echo "PROJ_DIR=gepa-next" >> "$GITHUB_ENV"
          else
            echo "PROJ_DIR=." >> "$GITHUB_ENV"
          fi
          echo "Using PROJ_DIR=${PROJ_DIR:-.}"
      
      - name: Show layout (debug)
        run: |
          pwd
          ls -la
          [ "$PROJ_DIR" = "gepa-next" ] && ls -la gepa-next || true

      - run: python -m pip install -U pip
      - name: Install deps
        run: |
          # core deps + sqlite persistence
          pip install \
            "fastapi>=0.111" "uvicorn>=0.30" \
            "pydantic>=2.7" "pydantic-settings>=2.3" \
            "httpx>=0.27" "pytest>=8.2" "pytest-timeout>=2.3.1" \
            "pytest-cov>=5.0" "aiosqlite>=0.20" \
            "ruff>=0.5.0" "mypy>=1.10" \
            "bandit>=1.7" "radon>=6.0"

      - name: Install Python client
        run: pip install -e clients/python

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: clients/js/package-lock.json

      - name: Build JS client
        run: |
          cd clients/js
          npm ci
          npm test
          npm run build
          cd ../..
      - name: Type check JS
        run: npx tsc -p clients/js/tsconfig.json --noEmit

      - name: Lint
        run: ruff check "$PROJ_DIR"

      - name: Type check
        run: |
          if [ -d "$PROJ_DIR/innerloop" ]; then
            mypy "$PROJ_DIR/innerloop"
          else
            echo "innerloop/ not found under $PROJ_DIR; skipping mypy"
          fi

      - name: Security scan
        run: bandit -r "$PROJ_DIR" -x "$PROJ_DIR/tests" -q

      - name: Complexity scan
        run: |
          radon cc -j "$PROJ_DIR"
          radon mi -j "$PROJ_DIR"

      - name: Tests (quick)
        run: pytest -q -k "health or sse" --maxfail=1
        env:
          PYTHONPATH: ${{ github.workspace }}/${{ env.PROJ_DIR }}
        working-directory: ${{ env.PROJ_DIR }}

      - name: Tests (full)
        run: pytest -q
        env:
          PYTHONPATH: ${{ github.workspace }}/${{ env.PROJ_DIR }}
        working-directory: ${{ env.PROJ_DIR }}

      - name: Upload examples
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: |
            examples/
            docs/postman/
