name: Formatting

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Black (check only)
        run: black . --check --diff
      - name: isort (check only)
        run: isort . --profile black --check-only --diff

  format-fix:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Black (auto-fix)
        run: black .
      - name: isort (auto-fix)
        run: isort . --profile black
      - name: Auto-commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format with black/isort"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          branch: ${{ github.ref_name }}
